--- #YAML:1.0
name:               App-CmdDispatch
version:            0.1
abstract:           Handle command line processing for programs with subcommands
author:
    - G. Wade Johnson <wade@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Tiny:     0
    Term::ReadLine:   0
    Test::Exception:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
